### ISSUE TITLE
特性请求：无图模式

### ISSUE THREAD

**Issue by gaoryrt** [Renovamen/Fishmail#5]
如题，急

**Comment by Renovamen** [comment]
已添加（[11469c4](https://github.com/Renovamen/Fishmail/commit/11469c4514d039a9849e7494e7e91e36987824e9)），点右上角的图标切换有图/无图模式：

![image](https://user-images.githubusercontent.com/29454156/118149729-6a5a2300-b444-11eb-87e8-8899d2f1256e.png)

**Comment by gaoryrt** [comment]
太快了！感谢您！
